site_name: Omesa
theme: readthedocs

repo_url: http://github.com/cmry/omesa
site_url: http://omesa.readthedocs.org/

site_description: Documentation for reproducible Text Mining research framework.


pages:
- [index.md, Home]
- [environment.md, Main, Environment]
- [experiment.md, Main, Experiment]
- [featurizer.md, Features, Featurizer]
- [dataloader.md, Backend, Dataloader]
- [processor.md, Backend, Taggers]
- [omesa.md, Examples, End-To-End]
- [df.md, Examples, Data-To-Features]
- [examples.md, Examples, Text Classification]
- [faq.md, Home]
