site_name: Shed Documentation
theme: readthedocs
docs_dir: sources
repo_url: http://github.com/cmry/shed
site_url: http://shed.readthedocs.org/
#theme_dir: theme
site_description: Documentation for reproducible Text Mining research framework.

dev_addr: '0.0.0.0:8000'

pages:
# - Home: index.md
- Main:
    - Environment: environment.md
    - Experiment: experiment.md
- Features:
    - Featurizer: featurizer.md
- Backend:
    - Dataloader: dataloader.md
    - Processor: processor.md
- Examples:
    - End-To-End: shed.md
    - Data-To-Features: df.md
    - Text Classification: examples.md
- FAQ: faq.md
